dad_o = input().split(' ')
dad_t = input().split(' ')
c1 = int(dad_o[0])
n1 = int(dad_o[1])
u1 = float(dad_o[2])
c2 = int(dad_t[0])
n2 = int(dad_t[1])
u2 = float(dad_t[2])
vt = ((n1 * u1) + (n2 * u2))
print(f'VALOR A PAGAR: R$ {vt:.2f}')
